#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY
# 固件首次开机自动执行：为 uhttpd 启用 HTTPS 监听并将 HTTP 重定向到 HTTPS

uci set uhttpd.main.listen_https='0.0.0.0:443'
uci add_list uhttpd.main.listen_https='[::]:443'
uci set uhttpd.main.redirect_https='1'
uci commit uhttpd

exit 0
