# SPDX-License-Identifier: MIT
# Xiaomi BE6500 Mesh 版固件（自动与手动触发）
name: XIAOMI-BE6500

on:
  # 与 BE12 Pro 一致：每日 Auto-Clean 完成后构建。
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string

permissions: write-all

jobs:
  config:
    name: XIAOMI-BE6500
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: XIAOMI-BE6500
      WRT_THEME: bootstrap
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: '12345678'
      WRT_IP: 192.168.123.1
      WRT_PW: 无
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: owrt
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: ${{inputs.PACKAGE}}
